### ISSUE TITLE
OSError When Generating Datasets

### ISSUE THREAD

**Issue by cywuuuu** [pdebench/PDEBench#11] opened 2022-11-12 15:37 UTC
i met this problem when i trying to run files like 

pdebench/data_gen/gen_xxx_xxx.py, it seems to be a problem of multithread? or just problem about file path?

```
Traceback (most recent call last):
  File "xxxx/pdebench/data_gen/gen_diff_sorp.py", line 101, in main
    pool.starmap(simulator, zip(repeat(config), seed))
  File xxxx/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "xxxx/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: Unable to open file (message not aligned)
```

thanks and i need your help 
o(╥﹏╥)o

**Comment by leiterrl** [comment] 2022-11-14 09:41
Hi,

I was unable to reproduce your error and there doesn't seem to be a whole lot of information about what this really means.

Could you try the following?

1. Manually set the number of cores that the mp.Pool uses to a low number (2 or 4) on line 98 of gen_diff_sorp.py
2. Also reduce the number of samples on line 96 to something small such as just 10

**Comment by leiterrl** [comment] 2022-11-25 14:50
Closing for now. Feel free to re-open if the issue persists.

**Closed by leiterrl** 2022-11-25 14:50 UTC
